# Common Affine Transform and their Inverses

In this demo, we take a look at several common affine transforms and calculate their inverses:

1. Scaling
2. Translation
3. Shearing
4. Rotation

In [15]:
import cv2
import numpy as np
import matplotlib.pylab as plt

## Inverses of common transforms
### Scaling

In [21]:
# Scale factors
cx = 0.5
cy = 0.5

# Our scaling matrix
A = np.array(
    [[cx, 0, 0],
    [0, cy, 0],
    [0, 0, 1]]
)
print(A)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  1. ]]


In [20]:
# let's take a look at the inverse
Ainv = np.linalg.inv(A)
print(Ainv)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]


### Translation matrix

In [28]:
# translation amounts (in pixels)
tx = 100
ty = 100

# Our translation matrix
B = np.array(
    [[1, 0, tx],
    [0, 1, ty],
    [0, 0, 1]]
)
print(B)

[[  1   0 100]
 [  0   1 100]
 [  0   0   1]]


In [24]:
# let's take a look at the inverse
Binv = np.linalg.inv(B)
print(Binv)

[[   1.    0. -100.]
 [   0.    1. -100.]
 [   0.    0.    1.]]


### Rotation matrix

In [26]:
# Define angle of rotation
angle = 45

# Convert to radians
angle = angle * np.pi / 180

# Define rotation matrix
R = np.array(
    [[np.cos(angle), -np.sin(angle), 0],
    [np.sin(angle), np.cos(angle), 0],
    [0, 0, 1]]
)
print(R)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [27]:
# let's take a look at the inverse
Rinv = np.linalg.inv(R)
print(Rinv)

[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


### Shearing matrix (vertical)

In [29]:
# Shear factors
sv = 0.5

# Define shear matrix
S = np.array(
    [[1, sv, 0],
    [0, 1, 0],
    [0, 0, 1]]
)
print(S)

[[1.  0.5 0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]]


In [30]:
# let's take a look at the inverse
Sinv = np.linalg.inv(S)
print(Sinv)

[[ 1.  -0.5  0. ]
 [ 0.   1.   0. ]
 [ 0.   0.   1. ]]
